config:
  api_keys:
    openai: "Your-OpenAI-KEY"
  llm:
    model_name: "gpt-4o-mini"
    temperature: 0
    max_tokens: 800
    presence_penalty: 0.0
    frequency_penalty: 0.2
    top_p: 1.0
  database:
    uri: "sqlite:///data/genai.db"


